___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [110]:
import numpy as np
import pandas as pd

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [54]:
my_list = [5, 10, 15, 20, 25]
np.array(my_list)


array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [55]:
np.zeros([5, 5])


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [56]:
np.ones([4, 4], dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [57]:
sevenS = np.ones([4, 4], dtype = int) * 7
sevenS


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [58]:
np.full([4, 4], 7, dtype = int)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [59]:
np.arange(2, 17, 2)


array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [60]:
np.arange(0,25).reshape([5, 5])


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [61]:
np.linspace(0, 25, 25, endpoint = False).reshape([5, 5])

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

### 10. Create randomly 5 numbers with numpy.

In [62]:
np.random.randint(0, 10, size=5)


array([7, 4, 2, 2, 3])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [63]:
np.random.standard_normal(size = 25).reshape([5, 5])


array([[ 0.37574266,  1.51493605, -0.90461725, -1.0792105 ,  1.58661176],
       [ 0.07183925,  0.55215508, -0.17794634, -0.91307328, -0.25487245],
       [ 1.77737295,  0.97121888, -2.28524638, -0.74612494,  0.31520656],
       [-1.20991535,  0.71836364,  1.77537974,  0.2479523 , -1.66790902],
       [-1.62246568, -0.35666302, -1.06436964, -0.14477208, -1.6421034 ]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [64]:
np.random.randint(20, 50, size = [3, 4])


array([[38, 46, 44, 37],
       [34, 48, 27, 34],
       [47, 22, 44, 25]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [65]:
ranarr = np.random.randint(0, 50, size = 48)
ranarr


array([17,  5, 13, 47, 19, 47, 22, 47, 30, 43, 12, 44, 17,  9, 28, 46, 31,
       14, 15, 45, 23,  5, 49,  3, 48, 23, 41,  7,  7, 32, 18, 42, 37, 38,
        3, 31, 43, 11, 40, 19,  2, 40, 46,  1, 23,  5, 44, 24])

In [66]:
ranarr.reshape((6, 8))


array([[17,  5, 13, 47, 19, 47, 22, 47],
       [30, 43, 12, 44, 17,  9, 28, 46],
       [31, 14, 15, 45, 23,  5, 49,  3],
       [48, 23, 41,  7,  7, 32, 18, 42],
       [37, 38,  3, 31, 43, 11, 40, 19],
       [ 2, 40, 46,  1, 23,  5, 44, 24]])

In [67]:
ranarr.shape = ((6, 8))
ranarr

array([[17,  5, 13, 47, 19, 47, 22, 47],
       [30, 43, 12, 44, 17,  9, 28, 46],
       [31, 14, 15, 45, 23,  5, 49,  3],
       [48, 23, 41,  7,  7, 32, 18, 42],
       [37, 38,  3, 31, 43, 11, 40, 19],
       [ 2, 40, 46,  1, 23,  5, 44, 24]])

In [68]:
ranarr * np.ones((6, 8))


array([[17.,  5., 13., 47., 19., 47., 22., 47.],
       [30., 43., 12., 44., 17.,  9., 28., 46.],
       [31., 14., 15., 45., 23.,  5., 49.,  3.],
       [48., 23., 41.,  7.,  7., 32., 18., 42.],
       [37., 38.,  3., 31., 43., 11., 40., 19.],
       [ 2., 40., 46.,  1., 23.,  5., 44., 24.]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [183]:
mat = np.arange(1, 17).reshape((4, 4))
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [184]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [185]:
mat[:,0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [186]:
mat[1]

array([5, 6, 7, 8])

### 17.Assign 77 to every cell in 3rd column.

In [193]:
mat[:,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [188]:
x = mat[1,0]
y = mat[3,2]
np.array([x, y])

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [75]:
# YOUR CODE IS HERE 


## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [194]:

mat
# YOUR CODE IS HERE 



array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [195]:
mat[mat < 10]

# YOUR CODE IS HERE 



array([1, 2, 4, 5, 6, 8, 9])

In [196]:
mat[mat > 12]
# YOUR CODE IS HERE 



array([77, 77, 77, 13, 14, 77, 16])

In [197]:
mat[mat < 10] + mat[mat > 12]




# YOUR CODE IS HERE 



array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [198]:
(mat[mat < 10] + mat[mat > 12]).std()




29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [199]:
mat = np.arange(1, 17).reshape((4, 4))

mat



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [207]:
mat[:,2] = [3, 7, 11, 15]

mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [208]:
mat[:,1].sum()


32

### 23. Get the median, mean and std of 3rd column in "mat".

In [209]:
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [210]:
column3 = mat[:,2]
column3


array([ 3,  7, 11, 15])

In [212]:
row3 = mat[2]
row3



array([ 9, 10, 11, 12])

In [214]:
print(np.median(column3))
print(np.median(row3))


9.0
10.5


In [215]:
print(np.mean(column3))
print(np.mean(row3))



9.0
10.5


In [216]:
print(np.std(column3))
print(np.std(row3))


4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [254]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [255]:
df = pd.read_csv('Salaries.csv')



In [256]:
df.head()



Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [257]:
df.sample()

Id  EmployeeName   JobTitle    BasePay  OvertimePay  OtherPay  \
44560  44561  Timothy Frye  Planner 4  106575.81          0.0       0.0   

       Benefits   TotalPay  TotalPayBenefits  Year  Notes         Agency  \
44560  41218.61  106575.81         147794.42  2012    NaN  San Francisco   

       Status  
44560     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [258]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [259]:
df.describe()



Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [286]:
df.groupby('Year')[['Year']].count()

Year
Year       
2011  36159
2012  36766
2013  37606
2014  38123

In [291]:
df['Year'].nunique()


4

In [292]:
df['Year'].unique()


# YOUR CODE IS HERE 



array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [294]:
df['TotalPay'].max()
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 



567595.43

In [295]:
df['TotalPay'].mean()
# YOUR CODE IS HERE 



74768.321971703

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [305]:
df_mean = df['TotalPay'].mean()
df[df['TotalPay'] > df_mean]

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [307]:
df[df['TotalPay'] > df_mean]['Id'].count()


69489

### How much does ALBERT PARDINI make money (including benefits)?

IndexError: Boolean index has wrong length: 1 instead of 148654

### Who is the lowest paid person?

In [268]:
# YOUR CODE IS HERE 



### What are the unique Jobs in dataset?

In [269]:
# YOUR CODE IS HERE 



### List the top 3 least common Jobs in the dataset.

In [270]:
# YOUR CODE IS HERE 



### How many people earned more than avg in 2012?

In [271]:
# YOUR CODE IS HERE 



### How many people have a title of Manager in their jobs?

In [272]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE 



### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [273]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [274]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [275]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________